
# Name your project! Project names should contain only lowercase characters
# and underscores. A good package name should reflect your organization's
# name or the intended use of these models
name: 'dbt_bronze'
version: '1.2'
config-version: 2

vars:
  # The 'table_name' variable will be accessible in all resources
  table_name: 'SOMETABLENAME'

# This setting configures which "profile" dbt uses for this project.
profile: 'SFdev'

# These configurations specify where dbt should look for different types of files.
# The `source-paths` config, for example, states that models in this project can be
# found in the "models/" directory. You probably won't need to change these!
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # directory which will store compiled SQL files
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"


# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_bronze:
    temp:
      +materialized: ephemeral
    raw:
      +materialized: table
      +schema: RAW
    status:
      +materialized: table
      +schema: ETL
    analytics:
      +materialized: table
      +schema: ANALYTICS
      


