{{
  config(materialized='incremental',
  pre_hook="delete from {{this}} where siteid=1 " 
  
  )
}}

SELECT CLIENT_NM, SITEID, SITETAG, SITENAME, SITEADDRESS1, SITEADDRESS2, SITECITY, SITESTATE, SITEZIP, SITEPHONE, FAX, SITEROOMS, SITEREGION, SITEOWNER, SITETYPE, SITELABEL, STARTDATE, BUD1FLAG, BUD2FLAG, BUD3FLAG, CURRENCYID, ACTIVE, BUD0FLAG, NAMESHORT, ISARCHIVED, ISCONSOLIDATED,current_timestamp row_insert_ts
FROM POC.LANDING.SITES
